##########################################
## Create Directory If It Does Not Exist.
## Required variables:
## -RML_anding_zone
##########################################

---
- name: Check RML Zone Exist
  stat:
    path: "{{RML_zone}}"
  register: lz

- name: Cleanning the RML zone
  shell: "rm -r {{RML_zone}}"
  when: lz.stat.exists

- name: Check RML Zone Exist
  stat:
    path: "{{RML_zone}}"
  register: lz2

- name: Create Directory If It Does Not Exist
  file:
    path: "{{RML_zone}}"
    state: directory
  when: not lz2.stat.exists