- name: Create Landing Zone
  include_role:
    name: installation
    tasks_from: Create_Landing_Zone.yml

- name: Copy Files In Landing Zone
  copy:
    src: "{{item}}"
    dest: "{{landing_zone}}"
  with_fileglob: "{{config_dir}}/*.*"

- name: Report Module Level.
  include_role:
    name: installation
    tasks_from: Report_Module_Backup.yml

- name: Copy Files In Landing Zone
  copy:
    src: "{{c_adx_sdt1}}adxcssdf.dat"
    dest: "{{config_dir}}"

