- name: Create RML ZONE
  include_role:
    name: installation
    tasks_from: Create_RML_Zone.yml

- name: Copy Files In RML Zone
  copy:
    src: "{{item}}"
    dest: "{{RML_zone}}"
  with_fileglob: "{{config_dir}}/*.*"

- name: Report Module Level.
  include_role:
    name: installation
    tasks_from: Report_Module_Backup.yml

