--- 
- name: Run python to creaate RCP
  command: python generate_rml_rcp_cmd.py -p AG
  args:
      chdir: "{{RML_zone}}"

- name: Run python to Run the RCP Job
  command: "run4690 -npp command.286 -c adxcsh0l backgrnd nnnn"
  args:
      chdir: "{{RML_zone}}"
  register: bckgrn
  ignore_errors: true

- name: Print RML
  command: python print_report_module_levels.py
  args:
      chdir: "{{RML_zone}}"
  register: RML
  ignore_errors: true

- name: Copy Files In RML Zone
  ansible.builtin.copy:
    src: "{{c_adx_sdt1}}adxcssdf.dat"
    dest: /home/ebossteam/RML/ojjo/
    owner: ebossteam
    mode: '0644'
    remote_src: true